Imports Microsoft.Office.Interop.Word

Public Class FrmWordLang

    Dim languages As New Dictionary(Of String, Integer) From {
        {"Afrikaans - South Africa", 1078},
        {"Albanian - Albania", 1052},
        {"Amharic - Ethiopia", 1118},
        {"Arabic - Algeria", 5121},
        {"Arabic - Bahrain", 15361},
        {"Arabic - Egypt", 3073},
        {"Arabic - Iraq", 2049},
        {"Arabic - Jordan", 11265},
        {"Arabic - Kuwait", 13313},
        {"Arabic - Lebanon", 12289},
        {"Arabic - Libya", 4097},
        {"Arabic - Morocco", 6145},
        {"Arabic - Oman", 8193},
        {"Arabic - Qatar", 16385},
        {"Arabic - Saudi Arabia", 1025},
        {"Arabic - Syria", 10241},
        {"Arabic - Tunisia", 7169},
        {"Arabic - U.A.E.", 14337},
        {"Arabic - Yemen", 9217},
        {"Armenian - Armenia", 1067},
        {"Assamese", 1101},
        {"Azerbaijani (Cyrillic)", 2092},
        {"Azerbaijani (Latin)", 1068},
        {"Bangla", 2117},
        {"Basque", 1069},
        {"Belarusian", 1059},
        {"Bengali (India)", 1093},
        {"Bosnian (Bosnia/Herzegovina)", 5146},
        {"Bulgarian", 1026},
        {"Burmese", 1109},
        {"Catalan", 1027},
        {"Cherokee - United States", 1116},
        {"Chinese - Hong Kong SAR", 3076},
        {"Chinese - Macao SAR", 5124},
        {"Chinese - People's Republic of China", 2052},
        {"Chinese - Singapore", 4100},
        {"Chinese - Taiwan", 1028},
        {"Croatian", 1050},
        {"Croatian (Bosnia/Herzegovina)", 4122},
        {"Czech", 1029},
        {"Danish", 1030},
        {"Divehi", 1125},
        {"Dutch - Belgium", 2067},
        {"Dutch - Netherlands", 1043},
        {"Edo", 1126},
        {"English - Australia", 3081},
        {"English - Belize", 10249},
        {"English - Canada", 4105},
        {"English - Caribbean", 9225},
        {"English - Hong Kong SAR", 15369},
        {"English - India", 16393},
        {"English - Indonesia", 14345},
        {"English - Ireland", 6153},
        {"English - Jamaica", 8201},
        {"English - Malaysia", 17417},
        {"English - New Zealand", 5129},
        {"English - Philippines", 13321},
        {"English - Singapore", 18441},
        {"English - South Africa", 7177},
        {"English - Trinidad", 11273},
        {"English - United Kingdom", 2057},
        {"English - United States", 1033},
        {"English - Zimbabwe", 12297},
        {"Estonian", 1061},
        {"Faroese", 1080},
        {"Filipino", 1124},
        {"Finnish", 1035},
        {"French - Belgium", 2060},
        {"French - Cameroon", 11276},
        {"French - Canada", 3084},
        {"French - Cote d'Ivoire", 12300},
        {"French - Democratic Rep. of Congo", 9228},
        {"French - France", 1036},
        {"French - Haiti", 15372},
        {"French - Luxembourg", 5132},
        {"French - Mali", 13324},
        {"French - Monaco", 6156},
        {"French - Morocco", 14348},
        {"French - North Africa", 58380},
        {"French - Reunion", 8204},
        {"French - Senegal", 10252},
        {"French - Switzerland", 4108},
        {"French - West Indies", 7180},
        {"Frisian - Netherlands", 1122},
        {"Fulfulde - Nigeria", 1127},
        {"Galician", 1110},
        {"Georgian", 1079},
        {"German - Austria", 3079},
        {"German - Germany", 1031},
        {"German - Liechtenstein", 5127},
        {"German - Luxembourg", 4103},
        {"German - Switzerland", 2055},
        {"Greek", 1032},
        {"Guarani - Paraguay", 1140},
        {"Gujarati", 1095},
        {"Hausa - Nigeria", 1128},
        {"Hawaiian - United States", 1141},
        {"Hebrew", 1037},
        {"Hindi", 1081},
        {"Hungarian", 1038},
        {"Ibibio - Nigeria", 1129},
        {"Icelandic", 1039},
        {"Igbo - Nigeria", 1136},
        {"Indonesian", 1057},
        {"Inuktitut", 1117},
        {"Irish", 2108},
        {"Italian - Italy", 1040},
        {"Italian - Switzerland", 2064},
        {"Japanese", 1041},
        {"Kannada", 1099},
        {"Kanuri - Nigeria", 1137},
        {"Kashmiri (Arabic)", 1120},
        {"Kashmiri (Devanagari)", 2144},
        {"Kazakh", 1087},
        {"Khmer", 1107},
        {"Konkani", 1111},
        {"Korean", 1042},
        {"Kyrgyz (Cyrillic)", 1088},
        {"Lao", 1108},
        {"Latin", 1142},
        {"Latvian", 1062},
        {"Lithuanian", 1063},
        {"Macedonian", 1071},
        {"Malay - Brunei Darussalam", 2110},
        {"Malay - Malaysia", 1086},
        {"Malayalam", 1100},
        {"Maltese", 1082},
        {"Manipuri", 1112},
        {"Maori - New Zealand", 1153},
        {"Marathi", 1102},
        {"Mongolian (Cyrillic)", 1104},
        {"Mongolian (Mongolian)", 2128},
        {"Nepali", 1121},
        {"Nepali - India", 2145},
        {"Norwegian (Bokmål)", 1044},
        {"Norwegian (Nynorsk)", 2068},
        {"Odia", 1096},
        {"Oromo", 1138},
        {"Papiamentu", 1145},
        {"Pashto", 1123},
        {"Persian", 1065},
        {"Polish", 1045},
        {"Portuguese - Brazil", 1046},
        {"Portuguese - Portugal", 2070},
        {"Punjabi", 1094},
        {"Punjabi (Pakistan)", 2118},
        {"Quecha - Bolivia", 1131},
        {"Quecha - Ecuador", 2155},
        {"Quecha - Peru", 3179},
        {"Rhaeto-Romanic", 1047},
        {"Romanian", 1048},
        {"Romanian - Moldova", 2072},
        {"Russian", 1049},
        {"Russian - Moldava", 2073},
        {"Sami", 1083},
        {"Sanskrit", 1103},
        {"Scottish Gaelic", 1084},
        {"Sepedi", 1132},
        {"Serbian (Cyrillic)", 3098},
        {"Serbian (Latin)", 2074},
        {"Sindhi - India", 1113},
        {"Sindhi - Pakistan", 2137},
        {"Sinhalese - Sri Lanka", 1115},
        {"Slovak", 1051},
        {"Slovenian", 1060},
        {"Somali", 1143},
        {"Sorbian", 1070},
        {"Spanish - Argentina", 11274},
        {"Spanish - Bolivia", 16394},
        {"Spanish - Chile", 13322},
        {"Spanish - Colombia", 9226},
        {"Spanish - Costa Rica", 5113},
        {"Spanish - Dominican Republic", 7178},
        {"Spanish - Ecuador", 12298},
        {"Spanish - El Salvador", 17418},
        {"Spanish - Guatemala", 4106},
        {"Spanish - Honduras", 18442},
        {"Spanish - Latin America", 58378},
        {"Spanish - Mexico", 2058},
        {"Spanish - Nicaragua", 19466},
        {"Spanish - Panama", 6154},
        {"Spanish - Paraguay", 15370},
        {"Spanish - Peru", 10250},
        {"Spanish - Puerto Rico", 20490},
        {"Spanish - Spain (Modern Sort)", 3082},
        {"Spanish - Spain (Traditional Sort)", 1034},
        {"Spanish - United States", 21514},
        {"Spanish - Uruguay", 14346},
        {"Spanish - Venezuela", 8202},
        {"Sutu", 1072},
        {"Swahili", 1089},
        {"Swedish", 1053},
        {"Swedish - Finland", 2077},
        {"Syriac", 1114},
        {"Tajik", 1064},
        {"Tamazight (Arabic)", 1119},
        {"Tamazight (Latin)", 2143},
        {"Tamil", 1097},
        {"Tatar", 1092},
        {"Telugu", 1098},
        {"Thai", 1054},
        {"Tibetan - Bhutan", 2129},
        {"Tibetan - People's Republic of China", 1105},
        {"Tigrigna - Eritrea", 2163},
        {"Tigrigna - Ethiopia", 1139},
        {"Tsonga", 1073},
        {"Tswana", 1074},
        {"Turkish", 1055},
        {"Turkmen", 1090},
        {"Uighur - China", 1152},
        {"Ukrainian", 1058},
        {"Urdu - India", 2080},
        {"Urdu - Pakistan", 1056},
        {"Uzbek (Cyrillic)", 2115},
        {"Uzbek (Latin)", 1091},
        {"Venda", 1075},
        {"Vietnamese", 1066},
        {"Welsh", 1106},
        {"Xhosa", 1076},
        {"Yi", 1144},
        {"Yiddish", 1085},
        {"Yoruba", 1130},
        {"Zulu", 1077}
        }

    Private Sub FrmWordLang_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Dim str_lang As String
        Dim array_L As Array 'Language.

        Try
            str_lang = My.Computer.FileSystem.ReadAllText("Wordlang.var")
            array_L = str_lang.Split("=")

            For Each lang In languages.Keys
                combLANGUAGE.Items.Add(lang)
            Next
            combLANGUAGE.Text = array_L(1)
        Catch
            str_lang = "1033=English - United States"
            My.Computer.FileSystem.WriteAllText("Wordlang.var", str_lang, False)
            MessageBox.Show("Word-language file is reset - try again", "Corrupt file", MessageBoxButtons.OK, MessageBoxIcon.Warning,
            MessageBoxDefaultButton.Button2, MessageBoxOptions.RightAlign)
        End Try
    End Sub

    Private Sub BtnAPPLY_Click(sender As Object, e As EventArgs) Handles btnAPPLY.Click
        Dim selectedLanguage As String = combLANGUAGE.SelectedItem.ToString()
        Dim languageID As Integer = languages(selectedLanguage)

        My.Computer.FileSystem.WriteAllText("Wordlang.var", languageID.ToString() + "=" + selectedLanguage, False)

        Try
            CheckSpelling(Form1.rtbARK, languageID)
        Catch ex As Exception
            MessageBox.Show("No Word exist" & vbCrLf & ex.Message, "Word error", MessageBoxButtons.OK, MessageBoxIcon.Warning,
            MessageBoxDefaultButton.Button2, MessageBoxOptions.RightAlign)
        End Try
    End Sub

    Private Shared Sub CheckSpelling(ark As RichTextBox, ID As Integer)
        Dim wordApp As New Application()
        Dim doc As Document = wordApp.Documents.Add()
        doc.Content.Text = ark.Text 'Laddar dokumentet med texten i rtbARK. 
        doc.Content.LanguageID = ID 'Ställer in språket för stavningskontroll.
        doc.CheckSpelling() 'Utför stavningskontroll.
        wordApp.Visible = True 'Aktivera Word-fönstret så att det flyttas längst fram.
        wordApp.Activate()
        doc.Close(False)
        wordApp.Quit()
    End Sub

End Class